FROM python:latest
ENV PYTHONBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE 1
RUN mkdir -p /home/app/webapp
WORKDIR /home/app/webapp
COPY requirements.txt /home/app/webapp
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
COPY ./django_app /home/app/webapp/
EXPOSE 8000
CMD python manage.py runserver
