version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - "./mysql:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: bbdd-python
      MYSQL_USER: samuel
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
